export {AbstractStatistic} from "@/igt-library/features/statistics/AbstractStatistic"
export {ArrayStatistic} from "@/igt-library/features/statistics/ArrayStatistic"
export {IgtStatistics} from "@/igt-library/features/statistics/IgtStatistics"
export {NumberStatistic} from "@/igt-library/features/statistics/NumberStatistic"
export {StatisticsSaveData} from "@/igt-library/features/statistics/StatisticsSaveData"
export type {StatisticsValue} from "@/igt-library/features/statistics/StatisticsValueType"
export {DictStatistic} from "@/igt-library/features/statistics/DictStatistic"

export {ArrayStatisticRequirement} from "@/igt-library/features/statistics/requirements/ArrayStatisticRequirement"
export {NumberStatisticRequirement} from "@/igt-library/features/statistics/requirements/NumberStatisticRequirement"
